server:
  address: localhost
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/apayo?characterEncoding=UTF-8&characterSetResults=UTF-8
    username: root
    password: dudgks56!!

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: none #create #애플리케이션 실행시점에 다 지우고 다시 생성
    properties:
      hibernate:
#        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug